### ISSUE TITLE
Add an option not to dim the status bar

### ISSUE THREAD

**Issue by adryft** [raatmarien/red-moon#61] opened 2016-05-10 16:02 UTC
Hello, I've used Darker Pro (a non-free screen filter) for a long time and would like to move to Red Moon as I believe the filter is better, however it lacks some features which are useful.
- ~~Automatically pause when installing APKs
  Darker detects when an APK is attempting to install and temporarily pauses.~~ See #64
- Notification panel buttons
  Easily enable/disable the filter via a button toggle instead of having to open the application. 
  (Red Moon's screenshots appear to show this functionality but it doesn't appear in Android 4.2.1 so I'm unsure if this is a bug.)
- Option to keep status bar brightness
  When enabled the filter works as usual except for over the status bar region. This is very useful for bandwidth monitoring or when apps have unclear icons.

Sorry to lump several queries into one issue but I thought it might be easier for you to dismiss if you weren't interested. Thank you for your work.

**Comment by Kasijjuf** [comment] 2016-05-10 17:51
Bullet point two should already be a feature.  Are you using the latest version?

**Comment by RomFouq** [comment] 2016-05-31 18:08
Automatically pausing for APKs would be awesome, since you need to pause the filter for updating apps on F-droid.

**Comment by raatmarien** [comment] 2016-07-02 11:33
Thanks for the suggestions!

> - Automatically pause when installing APKs
Darker detects when an APK is attempting to install and temporarily pauses.

This would indeed be very useful, and I've been looking into how to accomplish this. It seems that up to Android Lollipop (API 21) it was fairly easy to get the info of the foreground app with [ActivityManager.getRunningTasks](https://developer.android.com/reference/android/app/ActivityManager.html#getRunningTasks(int)), however as of API 21+ this only returns 'non sensitive' tasks, making it unusable for this purpose. 

According to [this StackOverflow answer](http://stackoverflow.com/a/33828821) a workaround on later versions of Android is using android UsageStatsManager and filter out the last used application. A problem with this approach is that UsageStatsManager isn't implemented on Samsung phones according to the comments on that question.

Lastly I'm not sure how Red Moon would register changes to the foreground activity. There doesn't seem to be a listener framework for the UsageStats or the ActivityManager and constantly polling for changes may be a drain on the battery life of a phone.

That said, I'm quite a fan of this feature. I think it would be a huge usability improvement (especially for F-Droid users). However it seems that it would be quite complex and time consuming to implement this correctly, which I don't have right now. If someone else is willing to implement this, I would love to see a pull request :smile:.

>- Notification panel buttons
Easily enable/disable the filter via a button toggle instead of having to open the application.
(Red Moon's screenshots appear to show this functionality but it doesn't appear in Android 4.2.1 so I'm unsure if this is a bug.)

If you don't have a pause/resume button on your notification, than it is a bug. If you don't have a enable/disable button in the notification anymore, than it is intended behaviour. 

I don't think a disable button is appropiate in the notification, since disabling and enabling should be a rare occurance for the normal user. If you use Red Moon once in a while, you should probably have it enabled. Disabling is meant as a way of removing all the Red Moon features for a while without uninstalling it.

>- Option to keep status bar brightness
When enabled the filter works as usual except for over the status bar region. This is very useful for bandwidth monitoring or when apps have unclear icons.

Although I do see the use of this feature, I think it would be very rarely used. Most people will want the whole screen to be dimmed when they are using Red Moon. I also don't think adding an option for this is a good idea, since I want to avoid feature creep and I don't want to 'scare' more casual users with too many options.

**Comment by raatmarien** [comment] 2016-07-02 11:46
I'm going to move your first suggestion to a separate issue for clarity.

**Comment by smichel17** [comment] 2017-03-08 06:02
I also do not think this is something we should add an option for. If there were a reliable way to detect whether the status bar is visible (ie, whether an app is full-screen), and just always apply the filter to the status bar at a slightly reduced level, I think that would be reasonable. But I am not confident such a thing exists.

**Comment by smichel17** [comment] 2017-04-26 22:33
> Easily enable/disable the filter via a button toggle

You should be able to do this via the notification. If you've added a widget and/or (on Android 7.0+) a quick settings tile, you can use them to toggle as well. If those aren't working, please open a bug about it :)

> Don't dim the status bar

Realistically, I just don't see this ever happening. Adding an extra option for a feature that I doubt will be used by the majority of users goes against Red Moon's design goal of staying as simple as possible. So, I'm going to close this issue.

That said, if something changes and this becomes a highly requested feature, I'm happy to reconsider it. And, if it is very important to someone, I encourage your to fork Red Moon and change it so the status bar is never filtered. It would be really, really easy to make and maintain that fork, because the logic for figuring out the screen dimensions is all in one file: https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/manager/ScreenManager.kt

**Closed by smichel17** 2017-04-26 22:33 UTC
Labels: wontfix
