### ISSUE TITLE
Why not supporting API level 15?

### ISSUE THREAD

**Issue by aurora-potter** [raatmarien/red-moon#157] opened 2017-07-08 19:12 UTC
Build your software for API level 26, but also make it available for API level 15.
You don't have to bring all the features to lower API devices.
You could use lots of android.support libraries and backward compatiblity practices to make Red Moon accessible for a wider range of devices.
You're losing a huge amount of users.
Look at the most popular softwares on Google Play and observe their minimum and target SDK versions.

**Comment by smichel17** [comment] 2017-07-08 22:05
Duplicate of #152

**Closed by smichel17** 2017-07-08 22:05 UTC
