### ISSUE TITLE
[Enhancement] Option to turn off status bar notification

### ISSUE THREAD

**Issue by DistantParadox** [raatmarien/red-moon#36] opened 2016-04-06 23:26 UTC
Adding an option to turn off status bar notifications would be a welcome improvement, so that once Red Moon is set up, it can be left alone to run in the background.

**Comment by smichel17** [comment] 2016-04-07 00:34
I do not know if this is still an issue on Android Marshmallow, but in previous versions the notification is needed so that Android doesn't decide to kill the app if the phone gets low on memory (unless @raatmarien has some trick that I don't know about up her sleeve).

However, you can hide the notification through Android system settings by going to 'app info' and unchecking "Snow notifications".

**Comment by smichel17** [comment] 2016-04-07 01:11
Twilight has a "setting" that (1) Has a popup telling the user what's about to happen and (2) Opens app info where the user can turn off notifications.

**Comment by bungabunga** [comment] 2016-04-07 05:15
Twilight also disables notification when the app is not active = during daytime.

**Comment by smichel17** [comment] 2016-04-07 05:28
@bungabunga do you mean Twilight Pro's experimental "Stop service outside filter times" setting?

**Comment by bungabunga** [comment] 2016-04-07 05:39
probably, i remember the notification wasn't present during daytime when i used Twilight (pro).

**Comment by smichel17** [comment] 2016-04-07 07:03
That makes sense -- I never used pro, and remember the notification always showing. I just skimmed Red Moon's code, and it seems like there's a way to set an alarm that will re-launch the service, so it might be possible to use that and turn the service off between filter times.

**Comment by raatmarien** [comment] 2016-04-07 11:59
It is indeed possible to have a setting to not show the notification when the filter is paused in Red Moon, since the service is technically only running when the filter is on. I could also create a preference for users to disable notifications altogether for Red Moon.

I'm however afraid that these settings may clutter the main activity, since I'd think the average user wouldn't want to change this. Would making an "More settings" preference screen with these options solve this?

**Comment by bungabunga** [comment] 2016-04-07 12:35
i think it's the best if the default setting is one that most people don't need to change. i belive that's: notification on when filter active, off when inactive and the "more settings/manual settings" for special purposes.

**Comment by smichel17** [comment] 2016-04-07 19:01
### Nothing actionable in this comment

There's a boatload of context, a much of which is rambling. I'll put the actionable stuff in the next comment. tl;dr: I understand why Twilight went with the design they have, but don't like where they ended up, so I'm looking for alternatives.

>i think it's the best if the default setting is one that most people don't need ever to change. 

These are my guidelines when it comes to settings:

- The user should not have to touch the settings in order to use the app.
  - This includes both initial setup and on an ongoing basis.
  - This one (esp. initial setup) applies less here since the app's main view is a settings page.
- Most users care about the same few, important settings. These should be easily accessible.
  - Corollary: Most users don't want to deal with other settings. We should minimize the amount of these.
- There are some niche users ("power users") who will want LOTS of custom configuration and detail.
  - It's hard to support these users *directly* without compromising the main experience.
  - We should still try to support them or (more feasible) enable them to support themselves.
    - I really like how Gnome 3 does this (though unfortunately it's not an approach that works on mobile): most (native) apps have a small number of settings accessible from within the app, but often have more settings that can be tweaked in dconf; there's no UI to change these settings. It means that most users have a simple and usable app, but niche users can still customize the app to meet their exact needs. I wish that 
    - Ex: on mobile this might mean exposing intents and breaking different screens into their own activities -- if a niche user wants a launcher that goes to a very specific screen, they can use [some other program](https://f-droid.org/repository/browse/?fdfilter=launcher&fdid=de.szalkowski.activitylauncher) to do that.
    - Obviously there's a limit to this: you don't want anybody to be able to break your app.

Note: sometimes (often) these principles conflict, and you just need to make a judgement call.

>It is indeed possible to have a setting to not show the notification when the filter is paused in Red Moon, since the service is technically only running when the filter is on. I could also create a preference for users to disable notifications altogether for Red Moon.

>I'm however afraid that these settings may clutter the main activity, since I'd think the average user wouldn't want to change this. Would making an "More settings" preference screen with these options solve this?

I like the idea of moving inessential settings behind a second level preference screen. However, I don't want to make the same mistake as Twilight, where those settings are all thrown in together and poorly explained (what's "Smart bulbs", anyway? ~~double rainbow~~ Philips HUE, what does it mean?).

>i believe [the default should be]: notification on when filter active, off when inactive and "more settings" or "manual settings" for special purposes.

>PS - that's my experience, maybe other people would like notification on all the time if they switch the filter on a lot during the day manually, i never feel the need to do so.

This is actually a more complicated setting than I originally thought. I see 3 settings worth supporting.

1. Notification on all the time. For those who want to micromanage, or have a way of checking if Red Moon is enabled.
  - This one is simple. If Red Moon is enabled, the notification is shown.
2. Notification always off, for users who want to fire and forget.
  - This one is slightly less simple. If the user selects this setting but leaves "Toggle Mode" set to Manual", then pauses the filter, they've essentially disabled Red Moon. If a user wanted to disable Red Moon, they'd do that. So:
    - [ ] "Always off" should not be selectable if "Toggle Mode" is "Manual"
  - I wonder if it would be better to do this the way Twilight did: just send users to the
3. Notifications on some of the time. As @bungabunga points out, this is probably what most users expect.
  - If the notification is on only when the filter is on, pausing the filter closes the notification. This is unexpected behavior for a default -- it's pause, not close.
    - This could be mitigated if there were "Pause for X minutes" buttons, but not solved. When I install apks, I hate looking at that white screen at night so I manually toggle the filter back on as soon as I hit 'install'.
  - Another option is that only _Automatic_ pause turns off the notification.
    - This is generally what I'd expect. The only difficulty is finding a good way to phrase this setting. Something like "Show only at night", except that if custom times are set, the filter might be on during the day.
  - A 3rd option is that we distinguish between "paused" and "stopped", where "stopped" means "paused and notification killed."
    - I'm concerned that users may be concerned about "stopped" vs "disabled". If started/stopped and enabled/disabled were the only options, it would be clear, but when there's also paused, it gets a little confusing.

**Comment by smichel17** [comment] 2016-04-07 21:58
Upon further reflection, I don't think we need a setting here.
- "Always hide notification" can happen via the system settings.
- A notification is a way to show status and to pause/unpause, not a launcher. An "always show notification" setting turns it into one. I don't think we should try to support that.
  - If a user wants to launch at consistent times every day, they should use automatic toggle.
    - If automatic toggle lacks important functionality, we should improve it.
  - If a user wants to launch the app at varying times but under consistent conditions (dark), we should support a dynamic filter based on lighting (in some ways, this is a better solution than toggle times).
  - If a user *really* just wants to frequently toggle the filter on and off at random times of the day, they should just use manual mode, leave the filter on all the time, and pause/resume as needed.

However, we do need a way to communicate when the notification will turn on and off. To do that, I propose introducing a new state: Stopped.

Note: I would finish #29, call that v3.0, then call this v3.1.

### Actionables:

- [ ] Re-add "Stop" button to notification drop-down.
  - It pauses the filter and kills the notification. No change to the power state.
- FAB affects the notification now, but its behavior is based only on the filter.
  - [ ] When the filter is on, pauses the filter and kills the notification. Uses the stop icon.
  - When the filter is paused, turns on the filter and the notification. Uses the current icon.
    - [ ] Confirm that no changes are needed to do this.
- [ ] "Resume at" setting -> "Start at. No functional change.
- [ ] "Pause at" setting -> "Stop at." Now pauses and kills the notification.

**Comment by raatmarien** [comment] 2016-04-11 11:00
Thanks for the detailed post @smichel17, it helps a lot.

I've been thinking about how to allow users to see the notification only when they need it, without complicating the UX.

I'm cautious of re-adding the stop button of v2.6.2 and earlier, because it complicates the state of Red Moon. I also think it would be ambiguous whether Red Moon would automatically turn the filter on when 'stopped'.

I think a solution might be to make the notification **not** persistent, when the filter is paused. That way, whenever a user feels that the notification clutters their notification tray, they can just slide it away like any notification (or use the 'remove all notifications' button). This would still allow a user to temporary pause the filter (to install something, or to look at a picture with accurate colours) and start it again simply from the notification.

Furthermore, I don't think Red Moon needs to introduce an additional state with this approach, since the notification works like the user learned from all other apps. I think most users would understand that when the notification is dismissed, it pops up again when the filter is turned on. This is analogous to dismissing the notification for one SMS message, with it popping up again for the next. It would also be clear that, to resume the filter, they just have to resume it from somewhere else.

For the power users that don't want a notification whatsoever when the filter is paused, a setting could be added under the "More settings" sub screen to "Dismiss the notification when the filter is automatically paused". There could also be a setting to disable the notification completely that directs the user to disable "Show notifications" in the app settings screen.

**Comment by smichel17** [comment] 2016-04-11 13:27
>I also think it would be ambiguous whether Red Moon would automatically turn the filter on when 'stopped'.

I don't think this would be the case, any more than it would be ambiguous whether Red Moon will automatically turn the filter on after you've dismissed a non-persistent notification.

>I think a solution might be to make the notification not persistent, when the filter is paused.

I think this is a great idea whether or not you implement a "stop" function.

>I'm cautious of re-adding the stop button of v2.6.2 and earlier, because it complicates the state of Red Moon.
[...]
>Furthermore, I don't think Red Moon needs to introduce an additional state with this approach

I think it does introduce a new state:

- Filter on
- Filter paused, notification shown
- NEW: Filter paused, notification dismissed
  - aka Stopped

I may have oversold "stopped is a new state" because of how it looks to the user. In the code,
```
stop() {
    pause();
    dismiss-notification();
}
```

>For the power users that don't want a notification whatsoever when the filter is paused, a setting could be added under the "More settings" sub screen to "Dismiss the notification when the filter is automatically paused".

I think normal users want this; "power users" are the ones who would want to use the filter during the daytime. So if you made the notification not persistent while paused, I'd also encourage you to make it automatically dismiss during the day.

Aside: I quote "power users" because I think the term is misleading. It implies that power user of app X is also a power user of app Y, and that the people who need particularly customized behavior are also particularly technically capable. In my opinion, thinking of them as a group of users with niche needs gives you a more realistic picture of who they are, which lets you design a better solution.

See the "thoughts" section of my earlier post: This issue is a great example of where we _could_ just say, "They're power users, let's throw in some options; they'll understand how to configure Red Moon how they like," -- or we could say, "There's a niche group of users who want Red Moon enabled during the day. Why do they want this and can we design a more elegant solution to meet their needs?"

>There could also be a setting to disable the notification completely that directs the user to disable "Show notifications" in the app settings screen.

I'd encourage you to implement the non-persistent notification and/or stop "state" before this, and wait to see if you get any feature requests for it. I suspect it may be a niche enough use that it's not worth adding a shortcut at all. That said, if you get a feature request request for this, I think it's reasonable to implement, for users who really just want to fire and forget.

**Comment by smichel17** [comment] 2016-04-11 13:45
If you go ahead and implement notification non-persistence, I'll send a MR (if you create a new branch, I'll send it there) to implement stopped state, and then you can try it out yourself and see if it's confusing.

other aside: I think the term "Pull request" is rather confusing to newcomers, though it makes total sense to anybody familiar with git, which is why I say MR instead of PR.

**Comment by raatmarien** [comment] 2016-04-11 14:43
>If you go ahead and implement notification non-persistence, I'll send a MR (if you create a new branch, I'll send it there) to implement stopped state, and then you can try it out yourself and see if it's confusing.

Great idea, thanks.

**Comment by smichel17** [comment] 2016-04-22 14:00
@raatmarien Note that this is still on my to-do list, just fairly low priority. Also:

Now that the notification is dismiss-able, I almost always dismiss it when I wake up & would like if that were the default behavior (only for automatic pause, and attached to the automatic pause action, not based on time of day). If the filter is paused manually it should become non-persistent like it is right now, and if the user opens Red Moon and starts the filter during the day time, it should appear again.

You could add a setting to make this behavior optional. I would recommend no setting, for the reasons from earlier in this thread (the setting is probably acting as a crutch for users to mitigate something we're doing something wrong / not doing that we should be), but if you're not comfortable with the no setting option, here are two ways to implement the setting, in order of preference:

1. "Always show notification" <- makes the notification persistent always. When this setting is unchecked, acts as I described above.
  - Advantage: clearer / more intuitive behavior
  - Disadvantage: means the user doesn't have the option to use the live behavior (persistent only when filter is running)
  - I would implement this as a **switch** because it causes an immediate, visible state change.
2. "Dismiss notification automatically" <- When checked, acts as I described above. When unchecked, acts like the live behavior
  - Advantage: pause + dismiss is always possible
  - Disadvantage: Always-persistent notification may be desirable for some users (as protection from accidentally dismissing the notification, especially with "dismiss all").
  - Disadvantage: while the behavior is intuitive, it's difficult to communicate quickly
    - You'd need some secondary text for clarification.
  - I would implement this as a **checkbox**. It changes functionality but has no immediate effect.

I'd put the new setting below "dark theme".

@DistantParadox @bungabunga could you weigh in on what you would expect the default behavior to be?

**Comment by smichel17** [comment] 2016-04-22 14:00
(Side benefit: I'd have a code example for exactly how to dismiss the notification, so I wouldn't need to go searching for one :P)

**Comment by raatmarien** [comment] 2016-04-23 09:22
>Now that the notification is dismiss-able, I almost always dismiss it when I wake up & would like if that were the default behavior (only for automatic pause, and attached to the automatic pause action, not based on time of day). If the filter is paused manually it should become non-persistent like it is right now, and if the user opens Red Moon and starts the filter during the day time, it should appear again.

I agree, I found myself doing this too. I've changed the behaviour of the AutomaticFilterChange receiver so it now automatically dismisses the notification if the filter is automatically paused.

>You could add a setting to make this behavior optional. I would recommend no setting, for the reasons from earlier in this thread (the setting is probably acting as a crutch for users to mitigate something we're doing something wrong / not doing that we should be), but if you're not comfortable with the no setting option, here are two ways to implement the setting, in order of preference:

I agree with you that this does not need a setting.

>(Side benefit: I'd have a code example for exactly how to dismiss the notification, so I wouldn't need to go searching for one :P)

For the implementation see here: https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/receiver/AutomaticFilterChangeReceiver.java#L73

**Comment by smichel17** [comment] 2016-05-03 17:31
@raatmarien Where did you get the fab icons? They're a different size than the notification ones. I can of course make ones that are the right size but that seems silly if they already exist somewhere.

**Comment by smichel17** [comment] 2016-05-03 20:47
@raatmarien I've started on this. Since I don't *really* know what I'm doing (and by that I mean I understand generally what's going on but not any nuance), I'm going slowly, doing things that I don't think should break anything. However, the latest commit causes crashes and I'm not really sure why. I added a new PendingIntent, COMMAND_STOP. First I made COMMAND_STOP=1 so it just gets caught by the stuff in place for COMMAND_OFF. Then I made it its own int (3), and duplicated all the code (I think) for catching COMMAND_OFF.

https://github.com/smichel17/red-moon/commits/feature_stop_state

**Comment by raatmarien** [comment] 2016-05-04 16:25
>@raatmarien Where did you get the fab icons? They're a different size than the notification ones. I can of course make ones that are the right size but that seems silly if they already exist somewhere.

The fab icons are exports of art/fab_start.svg, art/fab_pause.svg and art/fab_start_rtl.svg. I made those by resizing the art/start.svg, art/pause.svg and art/start_rtl.svg to 96x96, removing the padding that those icons have. 

>@raatmarien I've started on this. Since I don't really know what I'm doing (and by that I mean I understand generally what's going on but not any nuance), I'm going slowly, doing things that I don't think should break anything. However, the latest commit causes crashes and I'm not really sure why. I added a new PendingIntent, COMMAND_STOP. First I made COMMAND_STOP=1 so it just gets caught by the stuff in place for COMMAND_OFF. Then I made it its own int (3), and duplicated all the code (I think) for catching COMMAND_OFF. Any idea what I messed up?

>https://github.com/smichel17/red-moon/commits/feature_stop_state

I will take a look at your code to see if I can find the cause of those crashes.

**Comment by smichel17** [comment] 2016-05-04 16:51
For clarity, adding `COMMAND_STOP=1` and the other related changes (the first commit) doesn't change anything. It's only when I add it as a new intent that I try to catch separately that it crashes.

**Comment by raatmarien** [comment] 2016-05-04 16:58
@smichel17 It seems ScreenfilterPresenter was crashing [here](https://github.com/smichel17/red-moon/blob/feature_stop_state/app/src/main/java/com/jmstudios/redmoon/presenter/ScreenFilterPresenter.java#L164), because stopCommand was null. FilterCommandFactory returned null, because the command code exceeded VALID_COMMAND_END https://github.com/smichel17/red-moon/blob/feature_stop_state/app/src/main/java/com/jmstudios/redmoon/helper/FilterCommandFactory.java#L50. If you change [VALID_COMMAND_END](https://github.com/smichel17/red-moon/blob/feature_stop_state/app/src/main/java/com/jmstudios/redmoon/service/ScreenFilterService.java#L66) to 3, this bug should be fixed.

**Comment by smichel17** [comment] 2016-05-04 17:14
That was it, thank you!

**Comment by smichel17** [comment] 2017-02-22 13:36
I think the original reason for this issue (notification not automatically dismissed) has been long fixed, and the reason this has stayed open (removal of the distinction between paused and stopped) was just merged into master in #95. If there's a reason to re-open this, let me know.

**Closed by smichel17** 2017-02-22 13:36 UTC
Labels: enhancement
