### ISSUE TITLE
Bright flash when lowering brightness 

### ISSUE THREAD

**Issue by nikals** [raatmarien/red-moon#79] opened 2016-08-24 17:53 UTC
Checklist added by @smichel17. Original comment (not modified) is below.

- [ ] Gradually lower brightness as the filter fades in, instead of all at once

---

When I have the option "Lower Brightness" enabled and turn on red moon, the screen flashes bright as it restores the brightness to max before lowering it. 
Sony Xperia Z5

**Comment by raatmarien** [comment] 2016-09-19 17:19
Thanks for letting me know!

I'm not sure why this is happening, especially because Red Moon lowers the brightness before changing the brightness mode. I think this is a device specific bug, since I can't replicate it on any of my devices. If anyone can replicate and try to fix it, PR's are welcome.

**Comment by smichel17** [comment] 2016-09-19 21:53
I can replicate this on my Samsung galaxy S4 (SCH-i545). I'm a bit busy at the moment but I'll keep this on my radar. I don't use the lower brightness option

**Comment by smichel17** [comment] 2016-10-24 15:09
Hrm. I have always been able to replicate this, but now that I was going to look into it, I am unable to -.-

**Comment by smichel17** [comment] 2017-03-21 00:52
I think I figured this out.

There's two settings that control your phone's backlight: a brightness slider and an "automatic" checkbox. These are changed separately, but the behavior of your backlight depends on both.

So, when we turn off automatic brightness, in the instant before we lower the brightness slider, the backlight changes back to whatever the manual brightness setting was, which might be significantly brighter than it was when 'automatic' was enabled.

But, we can't just swap the order, because then we'll get a flash of brightness when we're turning off the filter. The solution is to change the level before the 'automatic' setting when we're dimming, and to restore them in the opposite order.

**Comment by smichel17** [comment] 2017-03-22 04:04
Turns out I was wrong. The order definitely makes a difference, but either way there is a flash of brightness. If anyone else has ideas, I'd love to hear them.

**Comment by smichel17** [comment] 2017-04-26 00:56
I did a fair amount of testing on my device. I set the dim and intensity to 0 and enabled `lower brightness`, then observed what happened when I toggled Red Moon at all (12) combinations of:

- Under a lamp / in pitch darkness
- Automatic brightness enabled / disabled
- Brightness slider at minimum / halfway / full
  - I also tested a couple other positions, but not all combinations

**It turns out that instantly lowering the brightness by a lot creates the illusion of a flash.** You can notice the same thing if you manually toggle automatic brightness. The illusion is strongest on the white parts of the screen. I had the most success at differentiating them by using the dark theme and covering all the white text, or looking at the light it generates when shining the screen on to something.

**I'm fairly confident that there was an actual bright flash, and that it is fixed in v3.0.0,** although it is difficult to be 100% sure.

So, there's nothing we can technically do better to avoid the flash. However, gradually adjusting the brightness slider down, then turning off automatic brightness, would go a long way towards breaking the illusion.

**Comment by smichel17** [comment] 2017-09-10 03:43
With the some code reorganization to prep for root mode, gradual fade turns out to be surprisingly difficult to add, so it's makes more sense to bundle this with #122 instead of trying to tack it on, now. So, closing this as a now-duplicate of #122.

**Closed by smichel17** 2017-09-10 03:43 UTC
Labels: enhancement
