### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by btimofeev** [raatmarien/red-moon#171] opened 2017-09-04 20:23 UTC
Red moon 3.1.0 from F-droid crashes on startup. Cleaning application data and reinstalling does not help. Version 3.0.0 works fine.

Android 6.0.1, Nexus 5

**Comment by Raketenwilli** [comment] 2017-09-04 20:33
Same. I don't know if this helps you but ALogcat says following:
--------- beginning of system
W/ResourcesManager(20994): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package null
W/System  (20994): ClassLoader referenced unknown path: /data/app/org.jtb.alogcat-1/lib/arm
W/ResourcesManager(20994): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package null
W/ResourcesManager(20994): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package null
D/AbsListView(20994): Get MotionRecognitionManager
E/MotionRecognitionManager(20994): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@98a2a8d
E/MotionRecognitionManager(20994): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@ed94442
E/MotionRecognitionManager(20994): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@ed94442
D/SecWifiDisplayUtil(20994): Metadata value : none
D/ViewRootImpl(20994): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{f683aa8 I.E...... R.....ID 0,0-0,0}
D/ViewRootImpl(20994): #1 mView = android.widget.LinearLayout{73059c1 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(20994): Timeline: Activity_idle id: android.os.BinderProxy@25a5c53 time:1937721497
D/ViewRootImpl(20994): #3 mView = null
V/ActivityThread(20994): updateVisibility : ActivityRecord{c8108aa token=android.os.BinderProxy@25a5c53 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(20994): #1 mView = android.widget.LinearLayout{392e838 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(20994): Timeline: Activity_idle id: android.os.BinderProxy@25a5c53 time:1937733399
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/AbsListView(20994): Get MotionRecognitionManager
D/ViewRootImpl(20994): #1 mView = android.widget.PopupWindow$PopupDecorView{6a70c75 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): #1 mView = android.widget.LinearLayout{806ea47 V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(20994): sendUserActionEvent() mView == null
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/AbsListView(20994): Get MotionRecognitionManager
D/ViewRootImpl(20994): #1 mView = android.widget.PopupWindow$PopupDecorView{2f42428 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): #1 mView = android.widget.LinearLayout{b952104 V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(20994): sendUserActionEvent() mView == null
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
V/ActivityThread(20994): updateVisibility : ActivityRecord{c8108aa token=android.os.BinderProxy@25a5c53 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(20994): #1 mView = android.widget.LinearLayout{532b91 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
I/Timeline(20994): Timeline: Activity_idle id: android.os.BinderProxy@25a5c53 time:1937777627
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
V/ActivityThread(20994): updateVisibility : ActivityRecord{c8108aa token=android.os.BinderProxy@25a5c53 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(20994): #1 mView = android.widget.LinearLayout{19c48df V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(20994): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(20994): Timeline: Activity_idle id: android.os.BinderProxy@25a5c53 time:1937787801
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): #3 mView = null
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(20994): ViewPostImeInputStage processPointer 1
V/ActivityThread(20994): updateVisibility : ActivityRecord{c8108aa token=android.os.BinderProxy@25a5c53 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
W/SELinux (22080): SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.jtb.alogcat 
D/TimaKeyStoreProvider(22080): TimaSignature is unavailable
D/ActivityThread(22080): Added TimaKeyStore provider
W/ResourcesManager(22080): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package null
W/System  (22080): ClassLoader referenced unknown path: /data/app/org.jtb.alogcat-1/lib/arm
W/ResourcesManager(22080): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package null
W/ResourcesManager(22080): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package null
D/AbsListView(22080): Get MotionRecognitionManager
E/MotionRecognitionManager(22080): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@98a2a8d
E/MotionRecognitionManager(22080): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@ed94442
E/MotionRecognitionManager(22080): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@ed94442
D/SecWifiDisplayUtil(22080): Metadata value : none
D/ViewRootImpl(22080): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{f683aa8 I.E...... R.....ID 0,0-0,0}
D/ViewRootImpl(22080): #1 mView = android.widget.LinearLayout{73059c1 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(22080): MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
D/ViewRootImpl(22080): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(22080): Timeline: Activity_idle id: android.os.BinderProxy@25a5c53 time:1937950116
D/ViewRootImpl(22080): #3 mView = null
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 1
D/AbsListView(22080): Get MotionRecognitionManager
D/ViewRootImpl(22080): #1 mView = android.widget.PopupWindow$PopupDecorView{e3f0576 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(22080): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(22080): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(22080): #3 mView = null
D/ViewRootImpl(22080): #1 mView = android.widget.LinearLayout{767415f V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(22080): sendUserActionEvent() mView == null
D/ViewRootImpl(22080): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
V/ActivityThread(22080): updateVisibility : ActivityRecord{68ee39d token=android.os.BinderProxy@25a5c53 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(22080): #3 mView = null
D/ViewRootImpl(22080): #1 mView = android.widget.LinearLayout{cbde3e3 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(22080): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(22080): Timeline: Activity_idle id: android.os.BinderProxy@25a5c53 time:1937965786
D/ViewRootImpl(22080): #3 mView = null

**Comment by smichel17** [comment] 2017-09-05 03:39
@Raketenwilli on a non-rooted device, ALogcat can only get its own logs. However, I was able to reproduce this in an Android 6.0 emulator, so they're not needed :)

**Comment by smichel17** [comment] 2017-09-05 03:54
Found [the bug](http://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/). Fixing it stops the crashes but there's other errors, too. I need to get to sleep tonight, but I should be able to figure this out tomorrow.

**Comment by Raketenwilli** [comment] 2017-09-05 12:45
@smichel17 didn't know this because one developer told me one time to do this also on a non rooted device. Thanks ;D

**Comment by smichel17** [comment] 2017-09-05 17:17
Fixed in c4d8723, it'll be in the next f-droid build.

**Closed by smichel17** 2017-09-05 17:17 UTC
Labels: bug
