### ISSUE TITLE
Filter ignores the timer completely

### ISSUE THREAD

**Issue by matteocoder** [raatmarien/red-moon#126] opened 2017-03-10 10:09 UTC
![screenshot_20170310-110159](https://cloud.githubusercontent.com/assets/22897138/23790912/56652546-0581-11e7-8396-7f6bd2ee55a6.png)

Even though the timer is on, you have to manually turn it on/off.

Moto G4 on 6.0.1 with Red Moon 2.10.0

**Comment by smichel17** [comment] 2017-03-10 14:26
I'll try to reproduce, but it worked on both my device and an emulator. Are you able to grab a logcat?

**Comment by matteocoder** [comment] 2017-03-10 14:45
I guess. What do I need to search for?

**Comment by smichel17** [comment] 2017-03-10 15:55
`TimeToggleChangeReceiver`, `ScreenFilterService`, and `TimeToggleFragment`.

**Comment by matteocoder** [comment] 2017-03-10 16:13
Ok, so this is what I did: 

1) I connected my phone to the computer in debug mode and turned on the filter, but with the timer **off**
2)  I executed `adb logcat` from the terminal
3) I turned the timer on

this is what I found
```
03-10 17:11:44.636  4150  4150 I RedMoonApplication: onPreferenceChanged: pref_key_automatic_filter
03-10 17:11:44.637  4150  4150 I TimeToggleFragment: Filter mode changed to true
03-10 17:11:44.638  4150  4150 I TimeToggleFragment: auto: true, useLocation: false, enabled: true
03-10 17:11:44.638  4150  4150 D TimeToggleChange: Canceling alarm to turn filter on
03-10 17:11:44.640  4150  4150 D TimeToggleChange: Scheduling alarm to turn filter on
03-10 17:11:44.641  4150  4150 I Companion: Scheduling alarm for java.util.GregorianCalendar[time=1489165244640,areFieldsSet=true,lenient=true,zone=Europe/Rome,firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2017,MONTH=2,WEEK_OF_YEAR=10,WEEK_OF_MONTH=2,DAY_OF_MONTH=10,DAY_OF_YEAR=69,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=6,HOUR_OF_DAY=18,MINUTE=0,SECOND=44,MILLISECOND=640,ZONE_OFFSET=3600000,DST_OFFSET=0]
03-10 17:11:44.642  4150  4150 D TimeToggleChange: Canceling alarm to turn filter off
03-10 17:11:44.644  4150  4150 D TimeToggleChange: Scheduling alarm to turn filter off
03-10 17:11:44.645  4150  4150 I Companion: Scheduling alarm for java.util.GregorianCalendar[time=1489213844644,areFieldsSet=true,lenient=true,zone=Europe/Rome,firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2017,MONTH=2,WEEK_OF_YEAR=10,WEEK_OF_MONTH=2,DAY_OF_MONTH=11,DAY_OF_YEAR=70,DAY_OF_WEEK=7,DAY_OF_WEEK_IN_MONTH=2,AM_PM=0,HOUR=7,HOUR_OF_DAY=7,MINUTE=30,SECOND=44,MILLISECOND=644,ZONE_OFFSET=3600000,DST_OFFSET=0]
```

**Comment by smichel17** [comment] 2017-03-10 16:20
Set the timer so it'll go on in one minute, then wait a full 60 seconds (the timer gets set for the same second as the minute you're in now, so it will go off 60 seconds later, even if you set it right before the minute changes) and see if it gets anything?

**Comment by matteocoder** [comment] 2017-03-10 16:35
then I set the filter to turn on at 17:29 and turn off at 17:30 and it worked perfectly. 
Maybe it was an update issue? I noticed that strange behavior reported above the morning after I updated the app. I usually keep my phone in airplane mode during the night and the phone is set to retrieve date and time from the network.

**Comment by smichel17** [comment] 2017-03-10 16:40
Do you normally use times from location or custom times?

**Comment by matteocoder** [comment] 2017-03-10 16:46
Recently I didn't use the location feature because of the bug from the previous version. The configuration you see on the screenshot was kept intact from the latest update to the moment we were troubleshooting.

**Comment by smichel17** [comment] 2017-03-10 16:49
Okay. Feel free to close this, or leave it open for a few days in case the bug reoccurs.

**Comment by matteocoder** [comment] 2017-03-10 16:54
I reinstalled the app just to make sure, then I set the filter to show up at 19:00 (it's 17:51 now) before turning the service on from the top toggle on the main screen. Then I turned on the service and the filter shows up regardless of that. I remember that it happened on previous versions of the app, but there was also a floating button on the lower right corner that paused/resumed the filter without turning the service off, so I would pause the filter if the time was not right and then at the right times the filter would show up/disappear. I see that in this new version there is no floating button though.

**Comment by smichel17** [comment] 2017-03-10 18:09
In the current version, if Red Moon is off\*, the service is not running\*\*. The switch does what the floating button used to do.

\*means the same thing as "if the filter is off" used to mean. See #121 for more info.

\*\*One exception: if the app is open, the service is running, so that the preview will start up faster, and to fix issues that could occur if the app got killed while it was running.

---

The switch was originally supposed to be a master switch. If it's off, Red Moon is guaranteed to be completely disabled. Like the switch on a power strip, or on the back of a desktop computer.

But the fact was, that it didn't actually do much. If the filter was off, the service was probably stopped too, even when the switch was on. The switch only really did two things:

- Allow you to easily disable and enable the timer while preserving your settings
  - This was useful. 
- Prevent you from manually turning on the timer
  - This was not useful and confusing to new users

Now that the timer settings are on their own page, there is a way to easily turn it off, so there wasn't much of a reason to keep the "master switch" functionality around, since all it did was hide the floating button and stop widgets from working (and it made the code more complicated than it needed to be).

**Comment by matteocoder** [comment] 2017-03-10 18:25
Oh I see now. Actually yes, I've noticed from `strings.xml` that the code looks a lot more organized now. Thanks for helping me! If everything goes smoothly tomorrow I'll close the issue.

**Comment by matteocoder** [comment] 2017-03-11 05:51
Unfortunately the problem is still present, though this time with location-based time: yesterday, when the filter was active, I set the timer to make the filter disappear by the time based on my location (6:29), but by 6:38 the filter was still on. 

What I had to do in order to make it work was to manually set the turn off time to 6:40.

**Comment by smichel17** [comment] 2017-03-11 15:39
So far, this seems to happen when using automatic times, not custom times. There are three possible places this bug could be:

1. The alarm is not being scheduled, when times from location is on. 
2. When times from location is on, the alarm is being scheduled for the wrong times.
3. The part of Red Moon that receives the alarm is never receiving it.
4. The alarm is received, but Red Moon is not turning on.

The relevant debug output will be in or near `TimeToggleTragment`, `LocationUpdateService`, `TimeToggleChangeReceiver`, and `ScreenFilterService`.

To get relevant debug information for each of those:

1. Turn on times from location and see if you get *any* logs from the receiver (which is also where scheduling happens).
2. Wait until Red Moon gets an updated location and get logs from the location update service and the receiver.
  - Right now it might take a while to get an updated location if your location services are not in high accuracy mode. 
  - The most reliable way to know *exactly* **when** Red Moon will get an updated location is this:
    - Open maps and start a navigation (or use any other app that explicitly uses an up to date location).
    - Go to location services and change them to gps only.
    - Open Red Moon and start searching for location
    - Turn off location services. The second you do this, Red Moon will update your location (but not before)
  - Weird steps, I know. We're intentionally triggering a bug in Red Moon's location update that can cause it to be really slow, paired with the fact that it will give up and use your phone's last known location (which we know is up to date from using maps) when you turn off location services.
3. Look at the log during the minute Red Moon is supposed to turn on and see if there is output, "alarm received".
4. If there is "alarm received", check for any output from the screen filter service right afterward.

**Comment by matteocoder** [comment] 2017-03-11 16:27
@smichel17 thanks for being so helpful.
so for step 1 I had my location turned off and when I activated automatic times this is the log I got:

`03-11 17:12:02.007  7739  7739 I RedMoonApplication: onPreferenceChanged: pref_key_use_location
03-11 17:12:02.007  7739  7739 I Companion: Received start request
03-11 17:12:02.011  7739  7739 I TimeToggleFragment: auto: true, useLocation: true, enabled: false
03-11 17:12:02.035  7739  7739 I LocationUpdateService: onCreate
03-11 17:12:02.036  7739  7739 I LocationUpdateService: Requesting location updates
03-11 17:12:02.036  7739  7739 I LocationUpdateService: List of providers + [passive, gps, network]
03-11 17:12:02.041  7739  7739 I LocationUpdateService: onStartCommand(Intent { cmp=com.jmstudios.redmoon/.service.LocationUpdateService }, 0, 1)
03-11 17:12:02.049  7739  7739 I LocationUpdateService: Location search failed, using last known location
03-11 17:12:02.058  7739  7739 I LocationUpdateService: onDestroy
`

when using method 2, this is the log I got:

``03-11 17:21:29.140  7739  7739 I RedMoonApplication: onPreferenceChanged: pref_key_use_location
03-11 17:21:29.140  7739  7739 I Companion: Received start request
03-11 17:21:29.144  7739  7739 I TimeToggleFragment: auto: true, useLocation: true, enabled: false
03-11 17:21:29.160  7739  7739 I LocationUpdateService: onCreate
03-11 17:21:29.160  7739  7739 I LocationUpdateService: Requesting location updates
03-11 17:21:29.161  7739  7739 I LocationUpdateService: List of providers + [passive, gps, network]
03-11 17:21:29.164  7739  7739 I LocationUpdateService: onStartCommand(Intent { cmp=com.jmstudios.redmoon/.service.LocationUpdateService }, 0, 1)
03-11 17:21:29.172  7739  7739 I LocationUpdateService: Location search failed, using last known location
03-11 17:21:29.188  7739  7739 I LocationUpdateService: onDestroy
03-11 17:21:29.199  7739  7739 I RedMoonApplication: onPreferenceChanged: pref_key_location
``
Interestingly, when trying method 2, even though location was on, Red Moon told me to "Enable location services to update location."

unfortunately today I won't be able to try method 3 and 4 because I won't be at home at that time. I'll follow up tomorrow and see what happens.

**Comment by smichel17** [comment] 2017-03-11 18:11
Do you see a line that looks like this one from your earlier log?

```
03-10 17:11:44.645  4150  4150 I Companion: Scheduling alarm for java.util.GregorianCalendar[time=1489213844644,areFieldsSet=true,lenient=true,zone=Europe/Rome,firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2017,MONTH=2,WEEK_OF_YEAR=10,WEEK_OF_MONTH=2,DAY_OF_MONTH=11,DAY_OF_YEAR=70,DAY_OF_WEEK=7,DAY_OF_WEEK_IN_MONTH=2,AM_PM=0,HOUR=7,HOUR_OF_DAY=7,MINUTE=30,SECOND=44,MILLISECOND=644,ZONE_OFFSET=3600000,DST_OFFSET=0]
```

**Comment by smichel17** [comment] 2017-03-11 18:39
> Interestingly, when trying method 2, even though location was on, Red Moon told me to "Enable location services to update location."

Yep, that's the bug (#107) we're intentionally triggering. There's two ways to get location: precise location using gps or approximate location using a network service (Google location services or one of the [UnifiedNlp](https://f-droid.org/repository/browse/?fdfilter=unified&fdid=com.google.android.gms) backends). These are separate android permissions.

Since Red Moon doesn't need your precise location and using the gps is battery-intensive, we used to only use the approximate location (also, it's a separate permission, and we want to request as few as possible). But, some users had phones with no network service installed, so in 2.10.0 we added the permission and use the gps -- but only if the phone doesn't have a network service installed. So, when your location services are turned on to gps only, red moon still tries to use the network service (which is turned off), and tells you to turn it on. Next patch we'll also do a check to see if gps is turned on, before we display the message.

**Comment by matteocoder** [comment] 2017-03-12 09:29
@smichel17 no I can't see either of those lines.

**Comment by smichel17** [comment] 2017-03-12 13:44
@matteocoder I think I know the issue (number 1 in the list above). If I'm right, the workaround is to

1. Make sure location services are turned on before you turn on `Times from location`
2. Stay on the timer page until the location finishes updating (including, don't open the notification panel).

**Comment by smichel17** [comment] 2017-03-12 16:26
@matteocoder The bug was that the timer was still being set from the timer screen, even though location updating happens in a service now. So if you left that screen too soon, the timer wouldn't get set even though the location got updated.

This is a hard bug for me to reproduce in order to test, because both my device and emulated devices find the location really quickly. I have what I think is a fix, which should be released today, and you can let me know if it works.

**Closed** 2017-03-12 16:30 UTC
Labels: bug

**Comment by matteocoder** [comment] 2017-03-12 16:37
@smichel17 thanks for being so helpful! What does the fix do to resolve the issue?

**Comment by matteocoder** [comment] 2017-03-12 18:09
Also the workaround worked :)

**Comment by smichel17** [comment] 2017-03-12 18:45
@matteocoder 

> What does the fix do to resolve the issue?

The actual fix is moving lines (the ones annotated with `@Subscribe`) from `TimeToggleFragment` to `RedMoonApplication`. There's a little bit of cleanup in there along with the fix.

And now here's the detailed answer with way more than you probably ever wanted to know. Sorry if that's too simple or too complicated; I'm not sure how much programming / Android dev you know, so I tried to write something readable to someone non-technical, but that also gave enough technical info to be useful to a programmer who wanted to get familiar with Red Moon's architecture.

---

- There's a class called `Context`, which gives you some information about the environment that the code is running in (for example, the theme), so you can respond dynamically to it.
- There's a class called `Application`, which is a special type of `Context`. Whenever your application is running, Android will automatically create an `Application` object. 
- Red Moon uses a framework called [EventBus](https://github.com/greenrobot/EventBus) for sending messages between different parts of the app (it's not accessible to other apps).
  - The overall design is: "something happens" -> the part of the app where it happened posts a message to the event bus -> any part of the app that's registered to receive that type of message is notified -> it does whatever it needs to
  - The idea here is that we can have a more functional style of programming instead of an imperative one. Ie, we can write code that describes how things should be, instead of writing code that describes how to do things.
    - Abstract example: What happens when we change a preference?
      - A typical (imperative) approach would be to attach some code to the preference that does everything that needs to happen when that preference changes.
      - With the event-based approach, the *only* thing we do is save the new value of the preference. A separate part of the app that's (always) listening for changes to preferences hears the change and sends a message about it. And then any part of the app can subscribe to those messages and react accordingly.

This is nice for things like making sure the main switch in the app is set correctly. It's tricky because the app might be open or closed. Events mean we don't need to care: when the filter turns on, we just post a message about it. The main screen in the app listens for that type of message and flips the switch when it hears one. If it's closed, it doesn't receive the message.

And even better: if we want to add another switch to toggle Red Moon, we don't need to change *any* other code. I actually did this recently. On Android 7.0+, we have a quick settings tile (like for toggling wifi, or airplane mode). It was just an icon that toggled the filter on click; it didn't reflect the current state. Here's the commit where I added that functionality (and updated the icon): https://github.com/raatmarien/red-moon/commit/7cd605cb211d96af53f66f98531a823fe5996500

> The only things you need to know to understand what's going on are:
> - `onStartListening` and `onStopListening` are called by the android system when you open and close the notification drawer
> - the EventBus `register` and `unregister` functions are to start and stop listening for messages.
> 
> It's pretty simple to set the state when you open the notification drawer. But what if you toggle the filter while the drawer remains open, via the notification? The `onFilterIsOnChanged` function listens for a message that the filter was toggled, and updates the state when it hears one. I didn't need to change the code that actually toggles the filter to also notify the tile about it.

Here's another example: The commit where I made the service stop if the filter is off when you close the UI: https://github.com/raatmarien/red-moon/commit/2a6b2e0be4ebb6033feb75450e7ab5eef56ba6b2

>The main UI doesn't need to know anything about whether the service is running\*\*, it just sends a message that it closed. The service listens for this message and stops itself -- but only if the filter is off. The commit includes a bunch of other listeners which I changed to use the same pattern (listen for messages only in relevant states, instead of always listening and only responding in some states). 

Anyway, back to your original question. Here was what happened pre-fix:

- Location service gets an updated location, and uses it to calculate updated sunset/sunrise times
-  updated location and times stored in prefs
- messages about updates posted to event bus
- `TimeToggleFragment` receives message about updated times, and calls the function to set the timer

We go wrong in the last step. If the TimeToggleFragment (the screen with timer preferences) isn't listening for messages (ie, because you left the screen), the timer never gets set. I made it so the `Application` object listens and sets the timer instead.

> \*By "preferences" I don't just mean user preferences. In the backend, preferences are the way of storing small amounts of persistent data (if you're storing large amounts you'd use a database), including, but not limited to, user preferences
>
> \*\*this is actually harder than you might think in Android, because when the system is running low on memory, anything can be killed at any time without a chance to save its state. The only thing guaranteed not to be killed is whatever app is currently open; apps are supposed to save their state when the user leaves them even if they keep running in the background

**Comment by smichel17** [comment] 2017-03-12 18:46
> Also the workaround worked :)

Now that you have the background, you also understand why it worked: you're making sure not to do anything that would cause the TimeToggleFragment to stop listening for updated location times.

**Comment by matteocoder** [comment] 2017-03-12 19:17
Thanks for the very detailed explanation!

**Comment by smichel17** [comment] 2017-03-12 19:20
At some point I'll take that and clean it up a bit and put it in a file in the repo

**Comment by matteocoder** [comment] 2017-03-21 15:37
@smichel17 This is probably the bug you were talking about recently, but I've found that in version 2.10.1, after tapping to search for location after the location is already set, the search will hang indefinitely, both with location set on "high accuracy" and on "battery saving". Here is the log:

03-21 16:18:41.364  9473  9473 I RedMoonApplication: onPreferenceChanged: pref_key_use_location
03-21 16:18:41.365  9473  9473 I LocationUpdateService: Received start request
03-21 16:18:41.369  9473  9473 I TimeToggleFragment: auto: true, useLocation: true, enabled: false
03-21 16:18:41.386  9473  9473 I LocationUpdateService: onCreate
03-21 16:18:41.386  9473  9473 I LocationUpdateService: Requesting location updates
03-21 16:18:41.387  9473  9473 I LocationUpdateService: List of providers + [passive, gps, network]
03-21 16:18:41.389  1487  5422 D IzatProviderEngine_jni: onAddRequest called by network
03-21 16:18:41.389  1487  5422 D IzatProviderEngine_jni: Provider Type: 2
03-21 16:18:41.389  1487  5422 D IzatProviderEngine_jni: Num Updates : 2147483647
03-21 16:18:41.389  1487  5422 D IzatProviderEngine_jni: Interval : 3
03-21 16:18:41.389  1487  5422 D IzatProviderEngine_jni: Displacement : 0.000000
03-21 16:18:41.389  1487  5422 D IzatProviderEngine_jni: Accuracy : 1
03-21 16:18:41.389  9473  9473 I LocationUpdateService: onStartCommand(Intent { cmp=com.jmstudios.redmoon/.service.LocationUpdateService }, 0, 1)
03-21 16:18:41.389  1487  4413 V OSNPGlue_jni: Entering  : void onSetRequestJNI(izat_manager::IzatRequest *)
03-21 16:18:41.408  1487  4457 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 uid=10034}
03-21 16:18:41.410  1487  4219 E WifiScanningService: Got invalid work source request: WorkSource{} from ClientInfo[uid=10034]

(if it's relevant, I've also turned off Wi-fi search when the Wi-fi radio is turned off). I posted this issue here because I didn't want to spam the issue section with similar issues, but if I need to open a separate one please let me know.

**Comment by smichel17** [comment] 2017-03-21 16:16
Let's wait for @raatmarien to release v2.10.2 and then check again. I made a bunch of changes in #107 that make location updating *much* smarter (to the point where I removed the ability to manually force a location update because it was no longer necessary).

**Comment by matteocoder** [comment] 2017-03-21 16:30
@smichel17 ok! Does that change something in the strings.xml file? I've made a new italian translation based on the recent changes in 2.10, but I'd like to keep it up to date with the code so that the app could provide a consitent experience when the language is set to Italian.

**Comment by smichel17** [comment] 2017-03-21 16:43
https://hosted.weblate.org/projects/red-moon/strings/it/

**Comment by smichel17** [comment] 2017-03-21 16:45
If you do translation on weblate it'll also be merged automatically.
