### ISSUE TITLE
Crash in secure apps (in-/ uninstalling)

### ISSUE THREAD

**Issue by Raketenwilli** [raatmarien/red-moon#179] opened 2017-09-11 21:40 UTC
I set the option to turn off filter in secure apps but every time I go in an secure app Red Moon crashes. Latest version on Android 6.0.1.

**Comment by smichel17** [comment] 2017-09-11 22:12
Thanks for the report. I think I know what the problem is, but just to be sure:

Does it happen in all secure apps or only the dialog to grant  permissions? Also, does it happen if the setting to pause in secure apps is turned off?

**Comment by Raketenwilli** [comment] 2017-09-12 13:07
No problem ;D

I think it happens in all secure apps. And to my surprise, I deinstalled one app with pause in secure apps off and it worked correctly, neither it crashed nor it stopped the deinstallation progress.

**Comment by smichel17** [comment] 2017-09-12 14:56
> I think it happens in all secure apps.

Oh, right, that. Fixed in 0495ec7, it'll be out in the next release.

There's also a (separate) bug where the filter will stop itself permanently when the permission dialog opens, fixed just now in 70b40b6.

> And to my surprise, I deinstalled one app with pause in secure apps off and it worked correctly, neither it crashed nor it stopped the deinstallation progress.

I believe that uninstall is not a secured action, so it'll work even when Red Moon is running. "Pause in secured apps" will pause for uninstall because we're currently just detecting what application is open, not which screen of the application. Planning to add that eventually but not in the near future -- see #174.

**Closed by smichel17** 2017-09-12 14:56 UTC
Labels: bug
