### ISSUE TITLE
Fade into filter

### ISSUE THREAD

**Issue by jcrowgey** [raatmarien/red-moon#98] opened 2016-11-15 06:54 UTC
More of a suggestion than an issue: what about a modality where the filter slowly gets more intense as time passes.  I'd love to have the color temp go redder and the dim get stronger as the evening goes on.  Say I start my filter around sunset and smoothly interpolate to whatever my max is at around 2 am.  I guess I've found that if I'm using my phone in bed in a dark room at midnight, I want a dimmer, redder filter than if I'm reading the news with my bedside light still on at 22:30.

The reverse would also be nice, maybe the filter starts going bluer an hour or so before sunrise.  I love the automatic settings to turn on/off at a given time, this idea is an extension of that mode.

I haven't looked at your code to see about implementation, but I thought I'd share this idea in case anyone else decides to pick it up and implement it.

Cheers and thanks for the app!

**Comment by smichel17** [comment] 2016-11-15 07:58
Duplicate of #33

**Comment by raatmarien** [comment] 2016-11-19 10:40
I do get the use case of a gradual transition of the filter, however I think that implementing something like this would complicate the code base and the UX of Red Moon, since an important feature of Red Moon is easy enabling and disabling of the filter at any time.

I'll close this issue to keep further discussion centralised in #33.

**Closed by raatmarien** 2016-11-19 10:40 UTC
