### ISSUE TITLE
Auto start/Stop Profile at user defined period

### ISSUE THREAD

**Issue by jerryn70** [raatmarien/red-moon#153] opened 2017-06-30 12:31 UTC
I have 3 different profiles. 
1. Reading Mode
2. Night Mode
4. Normal Mode

The modes should start like this, the night Mode starts from 6.30pm and ends at 10pm, and from 10.01pm to 6am reading mode needs to be active. From 6.01am to 6.30pm the normal mode.

So it will be great if you create an option to start and stop a profile at particular time period. 

_Sent from my Motorola XT1562 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by smichel17** [comment] 2017-06-30 12:50
I agree, this would be great. I currently do a similar thing using my phone's built-in filter. The filter goes on at sunset-ish, then Red Moon turns on automatically later in the evening. Of course, that only works if you have a recent version of Android, and I'd like more control as well, so I'm still interested in implementing it.

I'm going to close this issue as a duplicate of #106.

**Closed by smichel17** 2017-06-30 12:50 UTC
